### ISSUE TITLE
jlcpcb issue with BlueSCSI 1.1-a Desktop.stl

### ISSUE THREAD

**Issue by Rev-3ng** [erichelgeson/BlueSCSI#158]
I tried to order some of these on jlcpcb, but they sent back the following issue.

"As shown below, the ratio of length, width and height is more than 1:10, and there's a large empty area inside the model, there will be a high risk of deformation.

Will this risk be acceptable for you?"

![image](https://user-images.githubusercontent.com/108348223/185732490-3cd39279-7f83-41ec-bc69-429c448447ab.png)

**Comment by erichelgeson** [comment]
This is old - I've uploaded the current one we use here https://github.com/erichelgeson/BlueSCSI/blob/main/3D-Files/1.1/bluescsi11a_kerosmacmodsv2.stl.zip - I cant answer questions based on jlcbcb's 3d process. This stl works for us.
