### ISSUE TITLE
jlcpcb issue with BlueSCSI 1.1-a-DB25-Lid.stl

### ISSUE THREAD

**Issue by Rev-3ng** [erichelgeson/BlueSCSI#159]
I tried to order some of these with jlcpcb but they sent back the following issue:

"As shown below, the wall thickness like those indicated area are too thin which has a high risk of crack, loss, damage and deformation. Will this risk be acceptable for you?

If not, could you please kindly increase it to be at least 1.0mm to proceed? 2.0mm will be better."

![image](https://user-images.githubusercontent.com/108348223/185732581-2c3b0943-8ba9-4a4f-bfce-80fa328871d0.png)

**Comment by erichelgeson** [comment]
Hi, I'm not sure how to respond - it is thin but works. You may want to try to find a local maker space, library, or school that you can do some prints at instead.
