### ISSUE TITLE
Bootable in a AT machine?

### ISSUE THREAD

**Issue by jensma-de** [erichelgeson/BlueSCSI#197]
Hey there!
I'm trying to get a bluescsi running in an old AT machine.
The installation of DOS5 works fine, partitioning is no problem and setting the primary partition active also works without a hitch.

Unfortunatly I don't seem to be able to boot from the bluescsi. Is that normal? Or is there a trick to it =)?

Cheers!

**Comment by mynameistroy** [comment]
The ability to boot from a SCSI drive on a PC would be in the hands of the ROM on the SCSI card/chipset you are connecting to the BlueSCSI.

What is the hardware you are working with specifically?

**Comment by jensma-de** [comment]
![1](https://user-images.githubusercontent.com/95911770/202893574-8b38407c-d30b-4adc-a11c-ebcbc4437bd0.jpg)
![2](https://user-images.githubusercontent.com/95911770/202893577-71d93a76-8868-42d5-abb1-684a3bd996c7.jpg)

That's the machine :)
The SCSI controller is a NCR 53C400 and the BIOS for it resides in the eprom with the faded sticker "RT-BIOS".
Here's some info about it: https://forum.vcfed.org/index.php?threads/rancho-rt1000-8-bit-isa-scsi-controller-drivers-firmware.38039/

The PC seems to seek or wait endlessly for the bluescsi to boot, at least that's how I interpret the startup messages (or lack thereof)

**Comment by jensma-de** [comment]
Fixed - burned a newer SCSI BIOS and works now =)
