### ISSUE TITLE
Macintosh Classic compatibility with overclocked firmware

### ISSUE THREAD

**Issue by gingerbeardman** [erichelgeson/BlueSCSI#216]
- just a data point and to keep a record of this on GitHub
- I know there's not much point running this on a Classic 68K but one has to at least try :)

My Macintosh Classic setup shows "disk question mark" when running either 96MHz or 128MHz overlocked firmware. It's fine with the standard firmware.

BlueSCSI was flashed OK with no errors (though the DFU "Resetting USB to switch back to runtime mode" took a lot longer after flashing the overlocked firmwares) but the Mac won't see any drives through it. 

- I bought my BlueSCSI from flamelily UK if that helps 2022-04-11.
- Let me know if I can provide any additional logging.

**Comment by gingerbeardman** [comment]
For interests sake...

SCSI2SD
![image](https://user-images.githubusercontent.com/49612/215141657-1ed17df1-600e-4112-bd8d-ab1e105d6aa9.jpeg)

BlueSCSI
![image](https://user-images.githubusercontent.com/49612/215141269-b3c401d6-84bf-4fee-957c-647a0c478904.jpeg)

**Comment by erichelgeson** [comment]
Going to close this as the bluepill is likely just not able to run at the faster speed. OC is at your own risk and may or may not work - not much we can do from our side.
