### ISSUE TITLE
Contradictory max filename length documentation

### ISSUE THREAD

**Issue by ryandesign** [erichelgeson/BlueSCSI#217]
https://github.com/erichelgeson/BlueSCSI/wiki/Usage

This page says both:

> The naming convention is as follows (file name max 64 characters).

And:

> Bad
> 
> `HD99_712 foo bar fizz buzz bang.hda` Over 32 chars and invalid SCSI/LUN/Block size

What is the actual maximum filename length—32 or 64 characters?

**Comment by erichelgeson** [comment]
It was 32, and is now 64. It will say in your log.txt what it supports. I've updated to 64 on the docs.
