### ISSUE TITLE
Desktop 1.1 3d print link is dead

### ISSUE THREAD

**Issue by chrisdaun** [erichelgeson/BlueSCSI#234]
The like to the 3d printable mount files for the 1.1 desktop version is dead: https://github.com/erichelgeson/BlueSCSI/blob/main/3D-Files/1.1/bluescsi11a_kerosmacmodsv2.stl.zip

**Comment by erichelgeson** [comment]
Strange! Here it is for now:

[bluescsi11a_kerosmacmodsv2.stl.zip](https://github.com/erichelgeson/BlueSCSI/files/11412610/bluescsi11a_kerosmacmodsv2.stl.zip)

**Comment by chrisdaun** [comment]
Thanks @erichelgeson

**Comment by mitchkramez** [comment]
@erichelgeson this one doesn't seem to be what the bluescsi's came with, at least it doesn't work with a right angled connector - is there another version somewhere? I just went through all the branches and couldn't find a version that works with the right angled connector in any of them, but maybe i'm blind and totally missed it?

**Comment by erichelgeson** [comment]
[bluescsi11a_kerosmacmodsv2.stl.zip](https://github.com/erichelgeson/BlueSCSI/files/11789479/bluescsi11a_kerosmacmodsv2.stl.zip)

Right angle compatible - sorry i thought that other zip was the same.
