### ISSUE TITLE
SCSI cmd trace as per V2 Bluescsi.ini debug=1 option

### ISSUE THREAD

**Issue by z80micro-mc** [erichelgeson/BlueSCSI#235]
Is there a way to o/p SCSI cmd traces as per V2 when BlueSCSI.ini "debug = 1" is enabled to the log file on v1 ?

I am trying to debug BlueSCSI on RM Nimbus ( an MSDOS 80186 pc with old SASI / SCSI 1 controller, that does not support parity).

I suspect that part of my problems are to do with the lack of SCSI BUS drivers on V1 board and the inability of the STM32 to sink the required 38 mA per i/o pin to meet the SCSI BUS specs (The STM32 has a limit of 25 mA -> '0' voltage is too high > 0.8 v).

I would like to confirm that the logic is otherwise fine, if it is I'll hack a V1 to add a 74ALS638-1N 48mA SCSI BUS driver.

Passive term on controller <-> passive term on last drive  > 34 mA sink (for 0.8V '0')
Passive term <-> active term                                               > 29 mA sink (for 0.8V '0)
Active term  <-> Active term                                               > 29 mA sink

All of which is out of spec for STM32 (max 25 mA sink)

Peter

**Comment by erichelgeson** [comment]
> Is there a way to o/p SCSI cmd traces as per V2 when BlueSCSI.ini "debug = 1" is enabled to the log file on v1 ?

No. There is no such option in v1's ini file. To enable debug you must set [DEBUG ](https://github.com/erichelgeson/BlueSCSI/blob/main/src/BlueSCSI.cpp#L42)and recompile. Doing a check for every debug statement at runtime it would likely cause a performance hit.
